services:
  postgres:
    restart: always
    image: 'postgres:latest'
    ports:
      - '5433:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 5s
      retries: 5

  inventory:
    restart: always
    build: .
    command: 'uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload'
    env_file:
      - .env
    volumes:
      - '.:/src'
    ports:
      - '8001:8001'
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
